services:
  postgres:
    image: postgres:16-alpine
    container_name: items-postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres